### ISSUE TITLE
User John Doe

### ISSUE THREAD

**Issue by DevEngberg** [petr0n/BooksListed#8]
User needs to find out what the New York Times Best selling books were for last month.

Acceptance criteria:

- [x] index.html must have a clean, visual layout so that the drop down search box is easy to find

- [x] index.html needs to have a drop down box giving the user the ability to search for the best selling books for last month

- [x] must use javascript and jquery on click functionality for the user to interact with the site

**Comment by bpooladian01** [comment]
Checked boxes
